services:
  directus:
    image: directus/directus:latest
    secrets:
      - secret_key
      - admin_password
    ports:
      - 8080:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET_FILE: /run/secrets/secret_key
      ADMIN_EMAIL: "olesksandr.kushnir@marconirovereto"
      ADMIN_PASSWORD: /run/secrets/admin_password
      DB_CLIENT: "sqlite3"
      DB_FILENAME : "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"


secrets:
  secret_key:
    file: ./secrets/secret_key
  admin_password:
    file: ./secrets/admin_password
    